name: JFrog Pipelines

modules:
    activate:
    - index
    - concepts/04_jfrog_cli
    - labs/10_jfrog_cli
    - labs/11_jfrog_cli_repos
    - concepts/05_jfrog_aql
    - labs/20_jfrog_aql_samples
    - concepts/06_jfrog_graphql
    - concepts/07_jfrog_filespec
    - labs/30_jfrog_filespec_samples
    - finish
