#@data/values
---
credentials:
- portal_password: "TRAINING-PORTAL-PASSWORD"
  jfrog_accesstoken: "JPD_ACCESS_TOKEN"
  jfrog_url: "JPD_DOMAIN_NAME" (e.g. "myjpd.jfrog.io")
  jfrog_protocol: "JPD_PROTOCOL" (e.g. "https")
  