#@ load("@ytt:data", "data")

#@ for/end labenv in data.values.credentials:
apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: jfrog-pipelines-workshops
spec:
  portal:
    title: JFrog Pipelines Workshops
    logo: https://raw.githubusercontent.com/lsilvapvt/jfrog-pipelines-workshop/main/workshop/content/images/Jfrog_Green_RGB.png
    password: #@ labenv.portal_password
    ingress:
      domain: edu.workshops.zone
      hostname: jfrog
      class: contour
    registration:
      type: anonymous
    sessions:
      maximum: 3  
    catalog:
      visibility: public
  workshops:
  - name: jfrog-pipelines-fundamentals
    capacity: 2
    expires: 2h
    orphaned: 15m
    env:
    - name: LAB_SLOT_ID
      value: $(session_id)
    - name: JFROG_URL
      value: #@ labenv.jfrog_url
    - name: JFROG_PROTOCOL
      value: #@ labenv.jfrog_protocol
    - name: JFROG_ACCESSTOKEN
      value: #@ labenv.jfrog_accesstoken    
  - name: jfrog-pipelines-configuration
    capacity: 2
    expires: 2h
    orphaned: 15m
    env:
    - name: LAB_SLOT_ID
      value: $(session_id)
    - name: JFROG_URL
      value: #@ labenv.jfrog_url
    - name: JFROG_PROTOCOL
      value: #@ labenv.jfrog_protocol
    - name: JFROG_ACCESSTOKEN
      value: #@ labenv.jfrog_accesstoken    
