apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: jfrog-pipelines-fundamentals
spec:
  title: JFrog Platform Pipelines Fundamentals
  description: Fundamentals of JFrog Platform Pipelines
  url: https://github.com/lsilvapvt/jfrog-pipelines-workshop
  vendor: edu.workshops.zone
  authors:
  - Luciano Silva
  difficulty: intermediate
  duration: 1h
  tags:
  - jfrog
  - artifactory
  content:
    image: silval/jfrog-automation-workshop:latest
    files: github.com/lsilvapvt/jfrog-pipelines-workshop
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: true
      slides:
        enabled: false       
