apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: jfrog-pipelines-fundamentals
spec:
  title: JFrog Pipelines Fundamentals
  description: Fundamentals of JFrog Pipelines
  url: https://github.com/lsilvapvt/jfrog-pipelines-workshop
  vendor: edu.workshops.zone
  authors:
  - Luciano Silva
  difficulty: beginner
  duration: 1h
  tags:
  - jfrog
  - artifactory
  content:
    image: silval/jfrog-workshops-environment:latest
    files: github.com/lsilvapvt/jfrog-pipelines-workshop
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: false
      editor:
        enabled: true
      slides:
        enabled: false      
    env:
    - name: WORKSHOP_FILE
      value: workshop-intro.yaml 
  